services:
  web:
    build:
      context: ./web
      args:
        - NEXT_PUBLIC_BASE_PATH=
    ports:
      - "3000:3000"
    environment:
      - BOT_PUBLIC_KEY=
      - BOT_ENDPOINT=
      - YANDEX_CAPTCHA_SITE_KEY=
      - YANDEX_CAPTCHA_SECRET_KEY=
      - REDIS_URL=redis://redis:6379
      - KEYPAIR_DIR=/keypair
      - NEXT_PUBLIC_BASE_PATH=
    volumes:
      - ./keypair-web:/keypair
    restart: always
  redis:
    image: redis:alpine
    restart: always
    